### ISSUE TITLE
Matching parentheses make cursor invisible

### ISSUE THREAD

**Issue by ilikeorangutans** [aonemd/kuroi.vim#7]
Love this color scheme but when highlighting matching parentheses the cursor becomes invisible. 

Initial state, cursor between `()` and `{}`:
![image](https://user-images.githubusercontent.com/68387/102956836-e3150e80-44a6-11eb-8721-6e25b4bf3c32.png)
Moving one to the left:
![image](https://user-images.githubusercontent.com/68387/102956875-f922cf00-44a6-11eb-9b3f-61cad2804358.png)
The darker parentheses is where the cursor is, but it's very easy to spot. A brighter color more in line with the cursor might be better here!

**Comment by aonemd** [comment]
Hey @ilikeorangutans, thanks for opening this. I just pushed a fix for that.

**Comment by ilikeorangutans** [comment]
Fantastic, thanks so much for fixing this so quickly!
